spring.application.name=server

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/deskSpace_db?createDatabaseIfNotExist=true
spring.datasource.username=<SQLusername>
spring.datasource.password=<SQLpassword>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

jwt.secret=
jwt.expiration